Add cronjob for uw reopening offers
seattleflu/backoffice pull request #103
Opened 2020-12-02 20:28 UTC by jccraft-uw

As I noted as comments in the cron file, run this job at :15 and :55 after the hour.

redcap-det uw-reopening runs at  /10
etl fhir runs at /5
refresh-materialized-view shipping fhir_questionnaire_responses_v1 runs at /5

The offer job uses data from all 3 of those other jobs. Run this at :15 to use the :00 redcap-det uw-reopening run and at :55 to use the :40 redcap-det uw-reopening run.

2020-12-02 20:29 UTC, jccraft-uw commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make the cron job for the UW quota job](https://trello.com/c/pK9s4D7d/917-make-the-cron-job-for-the-uw-quota-job)

2020-12-03 18:01 UTC, kschwabefry commented on crontabs/id3c-production
> +15,55  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
Could we run this every half hour to space the runs out evenly? Perhaps  :15 and :45. The uw-reopening run is scheduled for every ten minutes on so it doesn't seem like we would have to target specific runs of that.

2020-12-03 18:23 UTC, jccraft-uw commented on crontabs/id3c-production
> +15,55  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
We need the 3 jobs to run to get all the data updated before we run the quota job. If we run quota before the materialization refresh has finished, for example, we risk allocating duplicate spots to the same queue entries.

2020-12-03 20:50 UTC, jccraft-uw commented on crontabs/id3c-production
> +15,55  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
Let's see here .... We want to run twice an hour. It if makes things saner, I'll space it out 30 minutes between runs. Running at :15 and :45 sounds fine with me. I'll make that change.

2020-12-03 21:46 UTC, kschwabefry commented on crontabs/id3c-production
> +15,55  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
Ok! Thanks Chris. I don't think I was following how :15 :55 minimized risk of assigning slots before the other jobs were complete was all.

2020-12-03 21:46 UTC, kschwabefry approved these changes

2020-12-03 22:57 UTC, tsibley approved these changes

2020-12-03 22:57 UTC, tsibley commented on crontabs/id3c-production
> +15,45  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
Looks like this is missing the `envdir` command before its `$ENVD/…` argument.

2020-12-03 22:57 UTC, tsibley requested changes
Whoops, fat-fingered the review status.

2020-12-04 01:05 UTC, jccraft-uw commented on crontabs/id3c-production
> +15,45  * * * * ubuntu promjob "id3c offer-uw-testing" fatigue --quiet $ENVD/redcap-sfs pipenv run id3c offer-uw-testing --commit
That would certainly make things work better. Added.

2020-12-04 02:19 UTC, jccraft-uw commented
> Whoops, fat-fingered the review status.

Thanks for calling it out. I fixed that and am deploying now and will babysit it.

2020-12-04 02:19 UTC, merged

2020-12-04 02:20 UTC, jccraft-uw commented
Deployed.