Switchboard enhancement
seattleflu/backoffice pull request #106
Opened 2020-12-07 23:00 UTC by jccraft-uw

2020-12-07 23:01 UTC, jccraft-uw commented
![](https://github.trello.services/images/mini-trello-icon.png) [scan-switchboard: make loading data more robust](https://trello.com/c/zwUaQ9fq/882-scan-switchboard-make-loading-data-more-robust)

2020-12-08 19:16 UTC, tsibley requested changes

2020-12-08 19:16 UTC, tsibley commented on crontabs/scan-switchboard
> +*/30 * * * * ubuntu promjob "switchboard refresh" chronic fatigue envdir $ENVD/redcap-sfs/ envdir $ENVD/redcap-scan/ flock /opt/scan-switchboard/data/record-barcodes.ndjson pipenv run make -BC /opt/s
All our other invocations of `flock` use its `--no-fork` / `-F` option to continue the exec-chain instead of forking the chain and using child processes. I think it'd be best to continue to do that here too.

2020-12-09 17:56 UTC, kschwabefry commented on crontabs/scan-switchboard
> +*/30 * * * * ubuntu promjob "switchboard refresh" chronic fatigue envdir $ENVD/redcap-sfs/ envdir $ENVD/redcap-scan/ flock /opt/scan-switchboard/data/record-barcodes.ndjson pipenv run make -BC /opt/s
There's text in the switchboard UI https://backoffice.seattleflu.org/switchboard/sfs-redcap that says "updated every 5 minutes" - which I think comes from https://github.com/seattleflu/scan-switchboard/blob/21cb1d6f0f3618aa72a4b8502faffd238c543002/datasette.yaml#L8 . @jccraft-uw do you mind making that change also to reflect the 30 minute refresh schedule?

2020-12-09 20:31 UTC, jccraft-uw commented on crontabs/scan-switchboard
> +*/30 * * * * ubuntu promjob "switchboard refresh" chronic fatigue envdir $ENVD/redcap-sfs/ envdir $ENVD/redcap-scan/ flock /opt/scan-switchboard/data/record-barcodes.ndjson pipenv run make -BC /opt/s
> All our other invocations of `flock` use its `--no-fork` / `-F` option to continue the exec-chain instead of forking the chain and using child processes. I think it'd be best to continue to do that here too.

Thanks for seeing that I missed the "-F", @tsibley . I've added it in.
@kschwabefry I've made the "updated every ... " change in the branch on the other repro. Thanks for seeing that.

2020-12-09 20:32 UTC, merged

2020-12-09 20:34 UTC, jccraft-uw commented
Deployed.