refresh-database: Exclude comments on extensions
seattleflu/backoffice pull request #113
Opened 2021-01-05 21:53 UTC by kairstenfay

Remove comments on extensions from the TOC when refreshing a target
database with a copy of the production database.

@tsibley pointed out that comments on extensions require a true
superuser, but RDS doesn't offer us that. Therefore, filter out comments
on extensions while preserving other comments (instead of using the
nuclear `--no-comment` option available in Postgres 11).

2021-01-05 21:54 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refresh id3c testing instance with new data](https://trello.com/c/bZhtlDMq/953-refresh-id3c-testing-instance-with-new-data)

2021-01-05 22:17 UTC, tsibley reviewed
When reviewing this PR, I noticed this existing code to make the error output nicer:

https://github.com/seattleflu/backoffice/blob/70b67f7cee6ede75f28b109d0a459b1a0fa22d45/dev/refresh-database#L240-L243

From the [log you pasted in Slack](https://seattle-flu-study.slack.com/archives/C0173B4S1LY/p1609808681024700?thread_ts=1609808492.024200&cid=C0173B4S1LY), it looks like that stopped working, maybe due to changes in error formatting?

2021-01-05 22:17 UTC, tsibley commented on dev/refresh-database
> +    pg_restore --list | grep -v 'COMMENT - EXTENSION' > production.toc
`pg_restore` still needs to be given the dump file as an argument.

2021-01-05 22:32 UTC, kairstenfay commented on dev/refresh-database
> +    pg_restore --list | grep -v 'COMMENT - EXTENSION' > production.toc
Ah, thanks for catching that.

2021-01-05 22:34 UTC, kairstenfay commented
> When reviewing this PR, I noticed this existing code to make the error output nicer:
> 
> https://github.com/seattleflu/backoffice/blob/70b67f7cee6ede75f28b109d0a459b1a0fa22d45/dev/refresh-database#L240-L243
> 
> From the [log you pasted in Slack](https://seattle-flu-study.slack.com/archives/C0173B4S1LY/p1609808681024700?thread_ts=1609808492.024200&cid=C0173B4S1LY), it looks like that stopped working, maybe due to changes in error formatting?

I noticed that, too, and was surprised to see that the silencing of noisy logs no longer worked. I forgot to look into it, but I'll see if I can re-align that code with the new error formatting now.

2021-01-06 03:38 UTC, kairstenfay reviewed
> > When reviewing this PR, I noticed this existing code to make the error output nicer:
> > https://github.com/seattleflu/backoffice/blob/70b67f7cee6ede75f28b109d0a459b1a0fa22d45/dev/refresh-database#L240-L243
> > 
> > From the [log you pasted in Slack](https://seattle-flu-study.slack.com/archives/C0173B4S1LY/p1609808681024700?thread_ts=1609808492.024200&cid=C0173B4S1LY), it looks like that stopped working, maybe due to changes in error formatting?
> 
> I noticed that, too, and was surprised to see that the silencing of noisy logs no longer worked. I forgot to look into it, but I'll see if I can re-align that code with the new error formatting now.

I added four spaces to the beginning of the `Command was: ` filter in the perl command to reflect the latest Postgres error formatting.

2021-01-06 03:38 UTC, kairstenfay commented on dev/refresh-database
> +    pg_restore --list | grep -v 'COMMENT - EXTENSION' > production.toc
Updated in the newest commit.

2021-01-06 03:39 UTC, kairstenfay commented
I don't think this code is working as expected, yet. I'm currently trying to refresh the testing database from my local machine, and while the Postgres TOC errors are no longer appearing, the job is hanging silently.

2021-01-07 20:01 UTC, tsibley reviewed
There's now two approaches in this code for suppressing ignorable errors:

1. Rewriting stdout/stderr by detecting when they occur.
2. Rewriting the TOC to avoid them from occurring in the first place

Approach 2 is cleaner in many ways, although does mean that the limitations of RDS instances get applied to local instances too, which is avoided by 1.

Notably, for comments on extensions, 1 is now redundant given 2.

We can't fully get away from 1 because of conditional role creation, but we could further reduce the scope of 1 by also filtering `TABLE DATA spatial_ref_sys` from the TOC.

2021-01-08 00:29 UTC, kairstenfay commented on dev/refresh-database
> +          (?-x:^\s{4}Command was: COPY public\.spatial_ref_sys .+?)\n+
Updated to use `\s*` in the latest version of the commit.

2021-01-08 00:30 UTC, kairstenfay commented
> There's now two approaches in this code for suppressing ignorable errors:
> 
>     1. Rewriting stdout/stderr by detecting when they occur.
> 
>     2. Rewriting the TOC to avoid them from occurring in the first place
> 
> 
> Approach 2 is cleaner in many ways, although does mean that the limitations of RDS instances get applied to local instances too, which is avoided by 1.
> 
> Notably, for comments on extensions, 1 is now redundant given 2.
> 
> We can't fully get away from 1 because of conditional role creation, but we could further reduce the scope of 1 by also filtering `TABLE DATA spatial_ref_sys` from the TOC.

Thanks for this feedback, @tsibley. I've also filtered `TABLE DATA spatial_ref_sys` in a new commit (that can likely be combined with the other `COMMENT - EXTENSION` commit) and removed the redundant regex logic to filter these errors from stdout/stderr. Please take a look and let me know if I have the right idea here.

2021-01-11 20:13 UTC, tsibley requested changes
Looks great! Thanks. One small detail in the TOC filtering, noted below.

2021-01-11 20:13 UTC, tsibley commented on dev/refresh-database
> +        | grep -v 'COMMENT - EXTENSION|TABLE DATA spatial_ref_sys' > production.toc
To use alternation (`|`) as-is you'll need to enable "extended regular expressions" with `-E`. The default is "basic regular expression", which treats `|` literally (but allows alternations via backslash escape as `\|`).

2021-01-11 20:44 UTC, kairstenfay commented on dev/refresh-database
> +        | grep -v 'COMMENT - EXTENSION|TABLE DATA spatial_ref_sys' > production.toc
Ah, thank you. I should have tested this change but forgot to because it runs for so long (on my machine, at least). 

I invoke the `-E` option in the latest comment.

2021-01-12 18:13 UTC, tsibley commented
I tested this locally and noticed the last commit wasn't working as intended. [Repushed](https://github.com/seattleflu/backoffice/compare/fd8375dff0cc92e94eaa0068076ad3f06c5d4ca1..c52aa3b7b67fe6aa6c7dfc47fe5dd84a6bab2030) to fix it.

2021-01-12 18:14 UTC, kairstenfay commented
> I tested this locally and noticed the last commit wasn't working as intended. [Repushed](https://github.com/seattleflu/backoffice/compare/fd8375dff0cc92e94eaa0068076ad3f06c5d4ca1..c52aa3b7b67fe6aa6c7dfc47fe5dd84a6bab2030) to fix it.

Thank you!

2021-01-15 19:44 UTC, tsibley approved these changes

2021-01-15 19:45 UTC, merged