Linelist merge error
seattleflu/backoffice pull request #124
Opened 2021-01-28 03:01 UTC by kairstenfay

Exit with a helpful message when duplicated barcodes are found in REDCap when creating the WA DOH Linelist export.

2021-01-28 22:11 UTC, kschwabefry requested changes

2021-01-28 22:11 UTC, kschwabefry commented on bin/wa-doh-linelists/transform
> +                f"{duplicated_collection_barcodes}")
Adding a more detailed and user-friendly exception is a great idea. I think recasting all MergeErrors may be too general here, as it can be caused by other situations beyond duplicated barcodes/non-unique merge key. If there aren't duplicates, the exception will still be thrown, with an empty dataframe for duplicated_collection_barcodes. In the case, we'd want to keep the details from the original merge error.

How about:

```
if duplicated_collection_barcodes.empty:
    raise #Re-raise original MergeException
else:
    raise Exception("Duplicate barcodes detected in project "
                f"{config['project_id']!r}: {config['name']!r}\n\n"
                f"{duplicated_collection_barcodes}")
```

2021-01-28 23:27 UTC, kairstenfay commented on bin/wa-doh-linelists/transform
> +                f"{duplicated_collection_barcodes}")
Great point. I had not considered that MergeErrors exist outside of the `validation` assertion failure. 

I just re-pushed following your suggestion.

2021-01-29 00:38 UTC, kschwabefry approved these changes

2021-02-18 17:10 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Linelists: Better merge error handling](https://trello.com/c/CCuh1Di1/1017-linelists-better-merge-error-handling)

2021-02-18 22:07 UTC, merged