redcap-data-dictionary: Rename id3c.cli method
seattleflu/backoffice pull request #135
Opened 2021-02-17 21:39 UTC by kairstenfay

In a new ID3C PR (209), we change the `redcap.metadata` and
`redcap.update_metadata` methods to use the term "fields" instead of
"metadata". Update the backoffice code accordingly.

-------------

Depends on https://github.com/seattleflu/id3c/pull/209

2021-02-18 17:11 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [id3c: post merge code review](https://trello.com/c/LIl76rfR/1018-id3c-post-merge-code-review)

2021-02-18 21:16 UTC, kschwabefry approved these changes

2021-02-23 00:42 UTC, tsibley requested changes

2021-02-23 00:42 UTC, tsibley commented on bin/redcap-data-dictionary/download-data-dictionary
> +    data_dictionary = project.fields()
`project.fields` is a property (attribute), not a method. (Although it's a property that's backed by a method.)

```suggestion
    data_dictionary = project.fields
```

2021-02-23 20:48 UTC, kairstenfay commented
Thanks for that suggestion, @tsibley. I just re-pushed to include it.

2021-02-23 23:33 UTC, tsibley approved these changes

2021-02-24 18:42 UTC, merged