[NEEDS TESTING][DO NOT MERGE] Add support for multiple output directories
seattleflu/backoffice pull request #167
Opened 2021-06-11 20:46 UTC by seidelma

This PR allows us to send linelist data to the state Department of Health via sft.wa.gov while also sending it to S3 as a backup. However, it is unsafe to merge this, because it requires a couple of pieces that are not in place yet:

- This requires the Python `fsspec` and `paramiko` modules, which are not installed on backoffice.seattleflu.org
- DoH has not yet provided us with a way to send them our SSH pubkey, so that will always fail
- S3 upload is as yet untested, because I don't have a safe way of doing that

2021-06-28 20:13 UTC, kschwabefry requested changes
Thanks for writing this PR Todd! I left a few comments throughout.

One other request for commits - it might be helpful to do a little git rebasing to clean up the story. I noticed that there were commits introducting the paramiko dependency and then undoing the depedency change. In other commits throughout, it might be helpful to  add descriptions about why the changes were made.

2021-06-30 15:33 UTC, seidelma commented on wa-doh-linelists/README.md
> +## Serving the web API
Nope, no wsgi here AFAIK. Since I just did a `cp -a id3c-production wa-doh-linelists; git add -A` it pulled that README.md from the former into the latter. I'll update the docs for wa-doh-linelists to reflect that.

2021-06-30 15:33 UTC, seidelma commented on wa-doh-linelists/env.d/README.md
> +# id3c-production/env.d
Yeah that's just a documentation edit, I'll take care of that.

2021-06-30 15:33 UTC, seidelma commented on bin/wa-doh-linelists/transform
> +             "local or remote path supported by the Python fsspec module.")
Will do!

2021-06-30 15:33 UTC, seidelma commented on bin/wa-doh-linelists/transform
> +    # This needs testing: different fsspec backends
Yes, but not to the prod sites. I scped a file from one host to another and uploaded some stuff to a test bucket. The idea here is to create a variable to handle the fsspec object because we first have to feed it whatever parameters are required (which are different depending on protocol), and then call the context manager (in common code) to actually create a file handle.

2021-06-30 15:33 UTC, seidelma commented on wa-doh-linelists/env.d/aliquot-manifest-processing/CONFIG
> +/opt/specimen-manifests/season-3-AWS-S3.yaml
That's true, we could probably share most if not all these files. When it became obvious that adding dependencies to the id3c-production pipenv was not going to be trivial, I just `cp -a`ed the whole pipenv into this new directory and edited what would obviously need to be changed for the linelist stuff. 

I'm not familiar enough with the codebase yet to say what's safe to share and what's not. But maybe it would be a good idea to create a `shared/env.d` directory so it's obvious that it's not specific to either id3c-production or wa-doh-linelists.

2021-06-30 15:33 UTC, seidelma commented on crontabs/Makefile
> +        wa-doh-linelists
Yes, it got committed later.

2021-06-30 15:33 UTC, seidelma commented on bin/wa-doh-linelists/transform
> +        filespec = fsspec.open(filename, mode='w')
That's true. However, I prefer to handle these things in a one-protocol-per-condition manner like a switch statement because I can quickly see which protocols are handled by a particular case and adding additional entries is really easy. Of course, if we don't expect there to ever be any protocol additions, that's kind of irrelevant; it's just a style thing and I'm happy to do it the other way too.

2021-07-08 22:48 UTC, kschwabefry commented
Looks good overall, thanks Todd for working on this.

One last thing you can do is to take another look over the commit history and do some rebasing for cleanup. 
For commits that revert other commits (https://github.com/seattleflu/backoffice/pull/167/commits/5da4fa4309e31a51b74de716a64431069fd9b022 and https://github.com/seattleflu/backoffice/pull/167/commits/206da9e8d8f8d0f8732ac37df6ae11819d57f0b5), it's helpful to rebase those so we don't have the back and forth change in the history on master branch. And similarly, for the small PR-related fixes like https://github.com/seattleflu/backoffice/pull/167/commits/f2ed117b81c932d0af396cbe5cca05849493b4ba and https://github.com/seattleflu/backoffice/pull/167/commits/6edd1ae99326ad90b547f4a599390493a7e04c3e , those can just be folded into the earlier relevant commits - they don't need to remain separate

2021-07-08 22:48 UTC, kschwabefry approved these changes

2021-07-14 19:04 UTC, merged