Switch S3 configs from Fred Hutch to BBI AWS account
seattleflu/backoffice pull request #223
Opened 2021-09-22 22:34 UTC by kschwabefry

We are migrating processes to the BBI AWS account as part
of consolidating the organization. Update the location of
various S3 files accordingly.

Migrate the configs for linelists, SCH and UW retros

2021-09-24 04:05 UTC, davereinhart requested changes
One other place where the FH S3 URL shows up: https://github.com/seattleflu/backoffice/blob/76a309c6270b6e8049141322b364d7b788f40ea2/bin/import-uw-retrospectives-to-redcap#L74

2021-11-24 00:48 UTC, kschwabefry commented on crontabs/wa-doh-linelists
> +0 6 * * * ubuntu promjob "wa-doh-linelists" chronic pipenv run envdir $ENVD/hutch envdir $ENVD/redcap /opt/backoffice/bin/wa-doh-linelists/generate --date $(date --date=yesterday --iso-8601=date) --o
Good suggestion, I've just reated `env.d/aws-bbi` and added the new access and secret keys there.

2021-12-08 00:40 UTC, davereinhart approved these changes

2021-12-10 01:21 UTC, merged

2021-12-10 01:49 UTC, kschwabefry commented
Deployed.

2021-12-10 17:48 UTC, kschwabefry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Transition FH S3 bucket to BBI Bucket](https://trello.com/c/LJIwCTP4/1175-transition-fh-s3-bucket-to-bbi-bucket)