Quiet Alerts for HCT Duplicate Barcodes
seattleflu/backoffice pull request #263
Opened 2022-01-22 01:09 UTC by bencap

With the HCT study team responsible for tracking duplicate barcodes in HCT, the duplicate alerts for the HCT study are no longer actionable and clog up the id3c-alerts channel. This change silences ROR duplicate barcode alerts when all duplicate barcodes are part of the HCT study (if duplicates are in other studies, or if they are duplicated across HCT and others, they will still be pushed to id3c-alerts). This change also moves duplicate barcodes in the EH&S job to info level logging instead of warning level. Duplicate netids in the EH&S job remain at warning level.

2022-01-25 00:00 UTC, davereinhart requested changes

2022-01-25 00:00 UTC, davereinhart commented on bin/return-of-results/transform
> +            print(f"{duplicates[list_of_cols].to_string(index=False)}", file=sys.stderr)
Rather than checking to see if all of the duplicate barcodes are from HCT, we can just filter the list to only print those that are non-HCT, which should be doable with a dataframe query.

2022-01-25 00:00 UTC, davereinhart commented on bin/uw-ehs-report/transform
> +
Is this additional logging needed, or will this same message be printed in the `drop_duplicate_values` function?

2022-01-25 02:07 UTC, bencap commented on bin/uw-ehs-report/transform
> +
Drop duplicate values is not used when dropping netids, but you are right that this is unnecessary.

2022-01-25 02:07 UTC, bencap commented on bin/return-of-results/transform
> +            print(f"{duplicates[list_of_cols].to_string(index=False)}", file=sys.stderr)
Thanks for the tips on this, new changes fix this!

2022-01-25 02:08 UTC, bencap commented
Made these changes and tried my hand at rebasing, for when you review again @davereinhart did I do that how I am supposed to?

2022-01-25 23:12 UTC, davereinhart commented on bin/return-of-results/transform
> +        duplicate_barcodes = list(duplicates_alerting['qrcode'].unique())
Not a blocker, but I think you already have these values in `non_hct_duplicates` so you should be able to use that rather than calling `unique()` on `duplciates_alerting`

2022-01-25 23:33 UTC, bencap commented on bin/return-of-results/transform
> +        duplicate_barcodes = list(duplicates_alerting['qrcode'].unique())
Ah true nice eye. Seems more logical to use that when I am explicitly printing non-HCT barcodes. Will change that rn.

2022-01-26 00:06 UTC, bencap commented
![](https://github.trello.services/images/mini-trello-icon.png) [Quiet duplicate barcode alerts for HCT](https://trello.com/c/PD7T69om/1271-quiet-duplicate-barcode-alerts-for-hct)

2022-01-26 19:34 UTC, davereinhart approved these changes

2022-01-26 21:26 UTC, merged

2022-01-26 21:28 UTC, bencap commented
deployed