Create pipeline for transferring Husky Testing results to EH&S
seattleflu/backoffice pull request #85
Opened 2020-09-25 22:15 UTC by kschwabefry

2020-09-25 22:16 UTC, kschwabefry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the pipeline that will produce the line list to send to EH&S](https://trello.com/c/DB4mfT7B/787-create-the-pipeline-that-will-produce-the-line-list-to-send-to-ehs)

2020-09-25 23:19 UTC, kairstenfay requested changes
Great start! I have a few requested changes for cleaning up some pieces that will standardize this tool alongside our others in `./bin/` and correct/update the documentation and usage of this. Thanks both!

One comment that doesn't fit elsewhere: 
can we rename this set of tools to `./bin/uw-ehs-report`? We name our other tools in `./bin/` using kebab-case.

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/generate
> +#
Can we add a description of the purpose of this file here? for example, like the header in `./bin/return-of-results/generate`

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/generate
> +    python3 "$bin"/import-to-uw-ehs-transfer-redcap.py --input-file "$datadir/uw_ehs_report.csv"
We can make `import-to-uw-ehs-transfer-redcap.py` executable by removing the `.py` and changing modifications (`chmod +x import-to-uw-ehs-transfer-redcap`). This will remove the need to invoke this script with `python3` and be more consistent with our other `./bin/` scripts.

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap
> +# You can optionally test with a different previous parse file (including the
This document header needs to be updated; it hasn't been changed since it was copied from the UW Retrospectives script.

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        help="An CSV file containing the data to import into EHS REDCap project")
Since this is the only argument, it can be positional, and therefore we don't have to specify `--input-file` before passing the CSV at runtime.

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +    REDCAP_API_URL = os.environ['REDCAP_API_URL']
If we check for these environment variables first thing (before reading in the CSV), then if they're missing, the script will abort before doing any computation.

2020-09-25 23:19 UTC, kairstenfay commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +    REDCAP_API_URL = os.environ['REDCAP_API_URL']
Additionally, this REDCap API Token has a suffix (TRANFSER_UW), but the one used in the other script (`export-redcap-uw-reopening`) does not. We should either give both of them a suffix to be consistent, or keep them both as `REDCAP_API_TOKEN` and pass the appropriate ones at runtime in the `generate` script, e.g. something like:
```sh
REDCAP_API_TOKEN=REDCAP_API_TOKEN_EHS_TRANSFER_UW "$bin"/import-to-uw-ehs-transfer-redcap
```

2020-09-25 23:32 UTC, joverlee521 reviewed
Great work team! Just have some minor comments, but the overall flow looks good 👍

2020-09-25 23:32 UTC, joverlee521 commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        return None
Do we want a warning log here that the import affected 0 records?

2020-09-25 23:32 UTC, joverlee521 commented on bin/uw_ehs_report/transform
> +    #assert all(enrollments['birthdate'].str.match(r"^\d{4}-\d{2}-\d{2}$").dropna())
Delete or uncomment?

2020-09-25 23:32 UTC, joverlee521 commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        help="An CSV file containing the data to import into EHS REDCap project")
Can we make this a positional argument instead of an optional argument since it's required? Then we don't need to include `--input-file` when we run the script.

2020-09-25 23:32 UTC, joverlee521 commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +        HuskyProject(23854, "REDCAP_API_TOKEN")
To match return of results, you can use the UW reopening specific token in `env.d/redcap-sfs/REDCAP_API_TOKEN_UW_REOPENING`

2020-09-25 23:32 UTC, joverlee521 commented on crontabs/uw-ehs-report
> +7,37 * * * * ubuntu pipenv run envdir $ENVD/redcap-uw-reopening/ envdir $ENVD/redcap-uw-reopening-ehs-transfer /opt/backoffice/bin/uw_ehs_report/generate
This seems like an arbitrary time... Can there be a comment with reason why it needs run at this time?

2020-09-26 00:21 UTC, jccraft-uw commented
> Great start! I have a few requested changes for cleaning up some pieces that will standardize this tool alongside our others in `./bin/` and correct/update the documentation and usage of this. Thanks both!
> 
> One comment that doesn't fit elsewhere:
> can we rename this set of tools to `./bin/uw-ehs-report`? We name our other tools in `./bin/` using kebab-case.

Done in the first commit since PR.
Oh man. kebab-case. Yet another case. Why can't the world settle on a case?!?

2020-09-26 00:21 UTC, jccraft-uw commented on bin/uw_ehs_report/generate
> +    python3 "$bin"/import-to-uw-ehs-transfer-redcap.py --input-file "$datadir/uw_ehs_report.csv"
Changed. Thanks for the details.

2020-09-26 00:22 UTC, jccraft-uw commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap
> +# You can optionally test with a different previous parse file (including the
That was in the first commit when I had copied files over from UW Retro.

2020-09-26 00:23 UTC, jccraft-uw commented on bin/uw_ehs_report/generate
> +    python3 "$bin"/import-to-uw-ehs-transfer-redcap.py --input-file "$datadir/uw_ehs_report.csv"
Done. Fixed in the file renaming fixup commit.

2020-09-26 00:24 UTC, jccraft-uw commented on bin/uw_ehs_report/generate
> +    python3 "$bin"/import-to-uw-ehs-transfer-redcap.py --input-file "$datadir/uw_ehs_report.csv"
The renaming is in that commit. The generate change is coming.

2020-09-26 00:42 UTC, jccraft-uw commented on bin/uw_ehs_report/generate
> +#
Added!

2020-09-26 00:42 UTC, jccraft-uw commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +        }
Thanks. Changed.

2020-09-26 00:42 UTC, jccraft-uw commented on bin/uw_ehs_report/generate
> +    python3 "$bin"/import-to-uw-ehs-transfer-redcap.py --input-file "$datadir/uw_ehs_report.csv"
Done!

2020-09-26 00:43 UTC, jccraft-uw commented on bin/uw_ehs_report/transform
> +    redcap_data['collection_via'] = redcap_data.apply(collection_via, axis='columns')
Sorry about that. That was leftover from an earlier iteration. Removed.

2020-09-26 00:43 UTC, jccraft-uw commented on bin/uw_ehs_report/transform
> +def drop_duplicate_values(input_series: pd.Series, label: str) -> pd.Series:
Oh nice! Thanks for that. Changed.

2020-09-26 00:44 UTC, jccraft-uw commented on bin/uw_ehs_report/transform
> +        id3c_data[field].replace({'t': 1, 'f': 0}, inplace=True)
Added the rationale.

2020-09-26 00:44 UTC, jccraft-uw commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +    "test_fulfillment_form_complete",
Sorry about that. That was leftover from an earlier iteration. Removed.

2020-09-26 00:44 UTC, jccraft-uw commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +    "illness_swabsend"
That was for something I almost have done. I removed these for now.

2020-09-26 00:44 UTC, jccraft-uw commented on bin/uw_ehs_report/transform
> +    #assert all(enrollments['birthdate'].str.match(r"^\d{4}-\d{2}-\d{2}$").dropna())
Uncommented!

2020-09-26 00:45 UTC, jccraft-uw commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +        HuskyProject(23854, "REDCAP_API_TOKEN")
Right on. Changed.

2020-09-26 01:00 UTC, kschwabefry commented on crontabs/uw-ehs-report
> +7,37 * * * * ubuntu pipenv run envdir $ENVD/redcap-uw-reopening/ envdir $ENVD/redcap-uw-reopening-ehs-transfer /opt/backoffice/bin/uw_ehs_report/generate
It was pretty much an arbitrary time :) I bumped it two mintues after the RoR pipeline which runs at 5 and 35. What do we default to normally? 0,30?

2020-09-26 01:22 UTC, jccraft-uw commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        help="An CSV file containing the data to import into EHS REDCap project")
Changed.

2020-09-26 01:22 UTC, jccraft-uw commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +    REDCAP_API_URL = os.environ['REDCAP_API_URL']
Added the env var check.
The REDCap API token names is still an open issue.

2020-09-26 01:22 UTC, jccraft-uw commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        return None
Added.

2020-09-26 01:23 UTC, jccraft-uw commented on bin/uw_ehs_report/import-to-uw-ehs-transfer-redcap.py
> +        help="An CSV file containing the data to import into EHS REDCap project")
Done!

2020-09-26 01:29 UTC, joverlee521 commented on crontabs/uw-ehs-report
> +7,37 * * * * ubuntu pipenv run envdir $ENVD/redcap-uw-reopening/ envdir $ENVD/redcap-uw-reopening-ehs-transfer /opt/backoffice/bin/uw_ehs_report/generate
Ahh. As long as there's no concrete reason why it has to run at this specific time, it's fine to leave as is.

2020-09-26 01:31 UTC, joverlee521 commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +        HuskyProject(23854, "REDCAP_API_TOKEN")
Thanks! Just need to change the `$ENVD/redcap-uw-reopening/` in crontabs to `$ENV/redcap-sfs`

2020-09-26 01:33 UTC, jccraft-uw commented on bin/uw_ehs_report/export-redcap-uw-reopening
> +        HuskyProject(23854, "REDCAP_API_TOKEN")
Just did it one second ago. See if the cron job commit is what you meant.

2020-09-26 01:34 UTC, kschwabefry commented on crontabs/uw-ehs-report
> +7,37 * * * * ubuntu pipenv run envdir $ENVD/redcap-uw-reopening/ envdir $ENVD/redcap-uw-reopening-ehs-transfer /opt/backoffice/bin/uw_ehs_report/generate
@joverlee521 Based on your phrasing, I'm reading this as a non-blocker? Could we check in about this next week, and update the job timing or comment in a follow up commit?

2020-09-26 01:51 UTC, joverlee521 approved these changes
Thank you for all your work on this @jccraft-uw  and @kschwabefry! 🎉

2020-09-26 02:31 UTC, kschwabefry commented
^ Just a rebase before merge, no content changes.

2020-09-26 02:31 UTC, merged