web: Add link to Lead Dawgs app
seattleflu/backoffice pull request #89
Opened 2020-10-15 17:24 UTC by kairstenfay

Link to the new /husky-musher/lead-dawgs app for streamlining kiosk
testing for UW Reopening.

Depends on https://github.com/seattleflu/husky-musher/pull/4

2020-10-15 17:25 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Kiosk Switchboard](https://trello.com/c/xrllFN31/834-kiosk-switchboard)

2020-10-19 17:18 UTC, tsibley requested changes

2020-10-19 17:18 UTC, tsibley commented on web/index.html
> +        <p>Streamline UW Reopening kiosk testing.</p>
```suggestion
        <p>Streamline Husky Coronavirus Testing kiosks.</p>
```

Let's strike "UW Reopening" from public-facing stuff in favor of the official name "Husky Coronavirus Testing".

2020-10-19 17:23 UTC, kairstenfay commented on web/index.html
> +        <p>Streamline UW Reopening kiosk testing.</p>
Makes sense to me!

2020-10-19 19:05 UTC, tsibley approved these changes

2020-10-19 19:37 UTC, merged