Add SFS Childcare to ROR
seattleflu/backoffice pull request #90
Opened 2020-10-15 23:56 UTC by joverlee521

* Generalize the UW-reopening REDCap export script to export any SFS longitudinal REDCap project that is defined in the `etc/sfs-longitudinal-redcap-projects.yaml` config file.

* Update the ROR transform script to required contacted field for SFS Childcare studies

* Check for duplicate barcodes across __all__ studies instead of just within each study arm.

2020-10-16 17:52 UTC, jccraft-uw commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +            record_id = record[project.record_id_field]
You could just use record.id since the getter uses the project.record_id_field internally.

2020-10-16 17:54 UTC, jccraft-uw commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +    fields = [project.record_id_field] + project.enrollment_fields
Nice to ensure that record_id is fetched!

2020-10-16 17:55 UTC, jccraft-uw commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +        record_id = record.pop(project.record_id_field)
Same here. You could just use record.id .

2020-10-16 17:57 UTC, jccraft-uw commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +    fields = [project.record_id_field] + project.encounter_fields
Same. I'm just so happy that I know how record.id works.

2020-10-16 17:58 UTC, jccraft-uw approved these changes
This looks really easy to read. Thanks for generalizing for longitudinal projects.

2020-10-16 18:18 UTC, joverlee521 commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +            record_id = record[project.record_id_field]
Ah thank you!

2020-10-16 18:19 UTC, joverlee521 commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +    fields = [project.record_id_field] + project.encounter_fields
I think this is the one case where I need to use `project.record_id_field` 😅

2020-10-16 18:25 UTC, jccraft-uw commented on bin/return-of-results/export-redcap-sfs-longitudinal
> +    fields = [project.record_id_field] + project.encounter_fields
Right. Sorry. You really want that field name here.

2020-10-17 16:28 UTC, jccraft-uw commented on etc/sfs-longitudinal-redcap-projects.yaml
> +  - week1_mon_test_arm_1
Notice that a secondary participant will get a test in the enrollment_arm_2 event. This event is both an enrollment and encounter event, so you should add enrollment_arm_2 to the encounter_event_names.

2020-10-17 16:29 UTC, jccraft-uw requested changes
See the note about how the enrollment_arm_2 event is both for enrollment and encounter.

2020-10-19 19:23 UTC, jccraft-uw approved these changes

2020-10-19 21:00 UTC, kairstenfay approved these changes
This is really cool, Jover! Thanks for refactoring this to take a config file. I haven't tested locally, but looking through the changes here, they look good to me. :+1:

2020-10-22 00:58 UTC, kschwabefry approved these changes
This looks really clean. Thanks for doing this Jover!

2020-10-26 20:35 UTC, joverlee521 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a backoffice export-redcap-childcare script](https://trello.com/c/XNECqRLX/853-create-a-backoffice-export-redcap-childcare-script)

2020-10-27 22:07 UTC, merged