Configurable cache
seattleflu/backoffice pull request #97
Opened 2020-10-28 18:25 UTC by kairstenfay

To be deployed in coordination with https://github.com/seattleflu/id3c/pull/180.

Bumps the frequency of the UW Reopening REDCap DET ETL to once every 10 minutes.

2020-10-28 18:26 UTC, kairstenfay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cache handling in REDCap → FHIR generation](https://trello.com/c/69EYeCSn/296-cache-handling-in-redcap-%E2%86%92-fhir-generation)

2020-10-28 19:08 UTC, joverlee521 requested changes
Just want to explicitly state that before this is deployed, we should copy the old `cache.pickle` file to the new cache files. 

The one requested change is to reconsider sharing the cache file between the Childcare and UW reopening studies.

2020-10-28 22:56 UTC, kairstenfay commented on crontabs/id3c-production
> +0 4-20/8 * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-asymptomatic-swab-n-send pipenv run id3c etl redcap-det asymp
Do you see a downside to the sharing? I don't but I'm certainly open here.

2020-10-28 22:57 UTC, kairstenfay commented on crontabs/id3c-production
> +21,51 * * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-childcare pipenv run id3c etl redcap-det childcare --fetch-bat
Are you suggesting that +1 minute is not long enough, and that we may want to run the Childcare ETL at, say, 24 and 54 after (as an example)?

I'm also OK with having our busiest and most frequent jobs have their own, separate cache (as in the case w/ UW Reopening).

2020-10-28 22:58 UTC, kairstenfay commented
> Just want to explicitly state that before this is deployed, we should copy the old `cache.pickle` file to the new cache files.

Great idea. Thank you.

2020-10-28 23:02 UTC, joverlee521 commented on crontabs/id3c-production
> +0 4-20/8 * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-asymptomatic-swab-n-send pipenv run id3c etl redcap-det asymp
No big deal, it's just so that we don't have to worry about new ETL jobs overlapping with the old ones. Since the old projects no longer get new participants, they don't need to have access to the cache of new addresses.

2020-10-28 23:06 UTC, joverlee521 commented on crontabs/id3c-production
> +21,51 * * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-childcare pipenv run id3c etl redcap-det childcare --fetch-bat
Right, the more I think about it, the more I lean towards just having a separate cache file for UW.

2020-10-28 23:08 UTC, kschwabefry commented
> > Just want to explicitly state that before this is deployed, we should copy the old `cache.pickle` file to the new cache files.
> 
> Great idea. Thank you.

Thinking through operational impacts of the cache changes: 
In decoupling the cache files (which, to be clear, I think is a net positive!), we potentially end up making some extra lookup calls with smartystreets. Seeding the new caches with the existing file will definitely mitigate the bulk of the extra calls, but there's also a (probably small?) number of additional lookups for addresses that exist in multiple projects that no longer share caches. Does the smartystreets service have hard limits (either in rate or overall volume) that we should be aware of?

2020-10-28 23:31 UTC, kairstenfay commented
> Thinking through operational impacts of the cache changes:
> In decoupling the cache files (which, to be clear, I think is a net positive!), we potentially end up making some extra lookup calls with smartystreets. Seeding the new caches with the existing file will definitely mitigate the bulk of the extra calls, but there's also a (probably small?) number of additional lookups for addresses that exist in multiple projects that no longer share caches. Does the smartystreets service have hard limits (either in rate or overall volume) that we should be aware of?

Right. Thanks for calling this out @kschwabefry. We have not yet been rate limited by Smarty Streets, but this could potentially happen if we're running jobs concurrently. SmartyStreets _does_ ask us to send bulk requests for geocoding which we're decidedly (because it was easier) _not_ doing, instead sending one-off address request lookups. Perhaps we should reconsider this design choice along with our cache handling changes.
We do have an overall volume lookup which was granted to us for our non-profit status. @tsibley has more details here, as he manages the SmartyStreets account. My understanding here is that we're not too worried about exceeding the overall volume of lookups allocated.

2020-10-29 00:12 UTC, kairstenfay commented on crontabs/id3c-production
> +0 4-20/8 * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-asymptomatic-swab-n-send pipenv run id3c etl redcap-det asymp
_You get a cache! And you get a cache!_

What might we call the cache for old ETLs? `old-cache`?

2020-10-29 00:12 UTC, kairstenfay commented on crontabs/id3c-production
> +21,51 * * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-childcare pipenv run id3c etl redcap-det childcare --fetch-bat
I pushed a new commit w/ a separate cache specifically for UW Reopening.

2020-10-31 04:06 UTC, tsibley commented
Great questions and answers, @kschwabefry and @kairstenfay. One niggle:

> My understanding here is that we're not too worried about exceeding the overall volume of lookups allocated.

Ah, not so! One of the primary reasons for having the cache in the first place is to avoid exceeding our overall lookup quota. The other primary reason is to avoid the significant time overhead of lookups for values we can already know.

2020-10-31 04:18 UTC, tsibley reviewed
A thought: we could use an environment variable defined in the crontab above each group of jobs to stop repeating ourselves, e.g.:

```
GEOCODING_CACHE=/home/ubuntu/sfs-cache.pickle
… flock -F $GEOCODING_CACHE envdir … id3c etl redcap-det … --geocoding-cache $GEOCODING_CACHE …
[more jobs]

GEOCODING_CACHE=/home/ubuntu/scan-cache.pickle
… flock -F $GEOCODING_CACHE envdir … id3c etl redcap-det … --geocoding-cache $GEOCODING_CACHE …
[more jobs]
```

Could even add `envvar = 'GEOCODING_CACHE'` to the `@click.option` to have it pull from there directly, instead of needing to specify `--geocoding-cache …` in the invocation.

A reminder: if the option name changes in https://github.com/seattleflu/id3c/pull/180, then those will have to reflected here.

A small note re: commit sequence: I think commits 1 and 3 could be combined. Fine to leave as-is, though.

2020-11-02 17:29 UTC, kairstenfay commented
> Great questions and answers, @kschwabefry and @kairstenfay. One niggle:
> 
> > My understanding here is that we're not too worried about exceeding the overall volume of lookups allocated.
> 
> Ah, not so! One of the primary reasons for having the cache in the first place is to avoid exceeding our overall lookup quota, especially because we reprocess all records from time to time via ETL revision bumps. (The other primary reason is to avoid the significant time overhead of lookups for values we can already know.)

Yes, I should have been clearer in my response. I agree that the reason we wrote a cache originally was to avoid exceeding our overall lookup quota. What I meant is that we're not as concerned about exceeding our overall quota when splitting our caches for separate jobs. Does that make sense?

2020-11-02 18:23 UTC, kairstenfay commented
> A thought: we could use an environment variable defined in the crontab above each group of jobs to stop repeating ourselves, e.g.:
> 
> ```
> GEOCODING_CACHE=/home/ubuntu/sfs-cache.pickle
> … flock -F $GEOCODING_CACHE envdir … id3c etl redcap-det … --geocoding-cache $GEOCODING_CACHE …
> [more jobs]
> 
> GEOCODING_CACHE=/home/ubuntu/scan-cache.pickle
> … flock -F $GEOCODING_CACHE envdir … id3c etl redcap-det … --geocoding-cache $GEOCODING_CACHE …
> [more jobs]
> ```
> 
> Could even add `envvar = 'GEOCODING_CACHE'` to the `@click.option` to have it pull from there directly, instead of needing to specify `--geocoding-cache …` in the invocation.
> 
> A reminder: if the option name changes in [seattleflu/id3c#180](https://github.com/seattleflu/id3c/pull/180), then those will have to reflected here.
> 
> A small note re: commit sequence: I think commits 1 and 3 could be combined. Fine to leave as-is, though.

I made the changes you suggested here and in https://github.com/seattleflu/id3c/pull/180, renaming the option to `--geocoding-cache` and accepting an environment variable named `GEOCODING_CACHE`.

2020-11-17 16:47 UTC, kairstenfay commented on crontabs/id3c-production
> +0 4-20/8 * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-asymptomatic-swab-n-send pipenv run id3c etl redcap-det asymp
I'm still curious about anyone's thoughts here. How many cache files do we want? What should they be named? etc.

2020-11-17 18:18 UTC, tsibley commented on crontabs/id3c-production
> +0 4-20/8 * * * ubuntu flock -F /home/ubuntu/sfs-cache.pickle envdir $ENVD/deidentification envdir $ENVD/smartystreets envdir $ENVD/redcap-asymptomatic-swab-n-send pipenv run id3c etl redcap-det asymp
I think the three cache files you configured (SCAN, HCT, everything else) are just fine for now. We can always tweak later.

2020-11-17 18:27 UTC, joverlee521 approved these changes

2020-11-17 18:42 UTC, kairstenfay commented
Rebased onto master branch

2020-11-17 20:46 UTC, merged